export const ADD_FONT = 'ADD_FONT';
export const CHANGE_CURRENT_FONT = 'CHANGE_CURRENT_FONT';

export const CHANGE_CURRENT_TARGET = 'CHANGE_CURRENT_TARGET';
export const CHANGE_COLOR_OF_TARGET = 'CHANGE_COLOR_OF_TARGET';